print("Hi! Let's make a band name!\n")
city = input("What city or town or whatever were you born in?")
print(city)
pet_name = input("What's a good name for a pet?\n")
print(pet_name)
print("I dub your band: " + city +" "+ pet_name)